"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.validateSpeechRequest = exports.WhisperAdapter = exports.MockSpeechProvider = exports.SpeechModuleService = exports.isSpeechError = void 0;
var types_1 = require("./types");
Object.defineProperty(exports, "isSpeechError", { enumerable: true, get: function () { return types_1.isSpeechError; } });
var speechService_1 = require("./speechService");
Object.defineProperty(exports, "SpeechModuleService", { enumerable: true, get: function () { return speechService_1.SpeechModuleService; } });
var mockSpeechProvider_1 = require("./providers/mockSpeechProvider");
Object.defineProperty(exports, "MockSpeechProvider", { enumerable: true, get: function () { return mockSpeechProvider_1.MockSpeechProvider; } });
var whisperAdapter_1 = require("./providers/whisperAdapter");
Object.defineProperty(exports, "WhisperAdapter", { enumerable: true, get: function () { return whisperAdapter_1.WhisperAdapter; } });
var validation_1 = require("./validation");
Object.defineProperty(exports, "validateSpeechRequest", { enumerable: true, get: function () { return validation_1.validateSpeechRequest; } });
